import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NumberRandomizer from "./NumberRandomizer";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>BOTCT Companion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://bloodontheclocktower.com/">Blood On The Clock Tower</a> Companion!
        </h1>
        <h3>
          <Link href="/NumberRandomizer">Number Generator</Link>
        </h3>
      </main>
    </div>
  );
};

export default Home;
